POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "kumar_atul",
    "password": "helloworld",
    "email": "atul@gmail.com",
    "phone": 9809809800
}

###

GET http://localhost:3000/