POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "kumar_atul",
    "password": "helloworld",
    "email": "atul@gmail.com",
    "phone": 9809809800
}

###

GET http://localhost:3000/

###

POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "anik_ghosh",
    "password": "helloworld",
    "email": "anik@gmail.com",
    "phone": 9809809800
}

###

POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "ravi",
    "password": "helloworld",
    "email": "ravi@gmail.com",
    "phone": 980943234
}

###
POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "ravi_nagraj",
    "password": "helloworld",
    "email": "ravinagraj@gmail.com",
    "phone": 980943234
}

###
POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "aravinaaa",
    "password": "helloworld",
    "email": "aravinaaa@gmail.com",
    "phone": 980943234
}

###
POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "erahull",
    "password": "helloworld",
    "email": "erahull@gmail.com",
    "phone": 980943234
}

###

